<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Address') ?></h2>
            </div>
            <div class="box-content">
				<?php $pickUp = null; ?>
				<?php $storeConfig = Mage::getStoreConfig('storepickup'); ?>
				<?php $storeSetting = $storeConfig['setting']; ?>
				<?php if($storeSetting['enable'] == 1 && $storeSetting['show_info_in_customer_shipping'] == 1) : ?>
					<?php $pickUp = Mage::helper('storepickup')->getStorePickUpByOrderId(); ?>
					<?php if(isset($pickUp['storepickup_id'])) : ?>
						<address>
						<?php echo $pickUp['title']; ?><br/>
						<?php echo $pickUp['address']; ?><br/>
						<?php echo $pickUp['city']; ?>, 
						<?php echo $pickUp['zipcode']; ?><br/>
						<?php echo Mage::helper('storepickup')->getCountryByCode($pickUp['country']); ?><br/>
						<?php echo $this->__('T : ') ?><?php echo $pickUp['phone_number']; ?><br/>
						</address>
						<?php else :  ?>
							 <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
						<?php endif; ?>
				<?php else :  ?>
					 <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
				<?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Method') ?></h2>
            </div>
            <div class="box-content">
                <!--show store pickup-->
                <?php if ($_order->getShippingDescription()): ?>
				<?php $orser_shipping = str_replace('|','<br/>',$_order->getShippingDescription()); ?>
                    <?php echo $orser_shipping; ?>
					<?php if($storeSetting['enable'] == 1 && $storeSetting['show_info_in_customer_shipping'] == 1) : ?>
						<?php if(isset($pickUp['storepickup_id'])) : ?>
							<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo $pickUp['latitude'] ?>,<?php echo $pickUp['longitude']; ?>&zoom=14&size=300x300&markers=color:red|label:S|<?php echo $pickUp['latitude']; ?>,<?php echo $pickUp['longitude']; ?>&sensor=false" />							
						<?php endif; ?>
					<?php endif;  ?>
				<?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>

